### ISSUE TITLE
PART handling

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#459]
(#, a, red, frog, 1). :|:
499
<{(*, red, frog, 1)} --> know>. :|:
5

(#, a, green, ant, 2). :|:
<(&/, (#, a, green, ant, 2), +501) =/> <{(*, ?x, ?y, 2)} --> know>>?

' triggers bugs in PART handling!

**Comment by patham9** [comment]
good find, and feel free to fix it yourself, it would be good for v3.0.1!

**Comment by patham9** [comment]
solved by https://github.com/opennars/opennars/commit/ef50447ab4b207b7b69b28fc99f5e17e094c668b

**Comment by PtrMan** [comment]
Still a problem because you just treated the effects - not the cause.

I'll fix the cause when I find the priority for it.
